name: Deploy Client

on:
    push:
        branches:
            - "main"
            - "develop"
            - "feature/*"
jobs:
    deploy:
        name: Deploy Client
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
                working-directory: client
        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: npm i && npm run build && deploy
              run: npm i && npm run build
              
           